// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CampusBridgeDbContext))]
    [Migration("20260718113729_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubStudent", b =>
                {
                    b.Property<string>("ClubsClubId")
                        .HasColumnType("text")
                        .HasColumnName("clubs_club_id");

                    b.Property<string>("StudentsStudentId")
                        .HasColumnType("text")
                        .HasColumnName("students_student_id");

                    b.HasKey("ClubsClubId", "StudentsStudentId")
                        .HasName("pk_club_student");

                    b.HasIndex("StudentsStudentId")
                        .HasDatabaseName("ix_club_student_students_student_id");

                    b.ToTable("club_student", (string)null);
                });

            modelBuilder.Entity("CollegeTeacher", b =>
                {
                    b.Property<string>("CollegesCollegeId")
                        .HasColumnType("text")
                        .HasColumnName("colleges_college_id");

                    b.Property<string>("TeachersTeacherId")
                        .HasColumnType("text")
                        .HasColumnName("teachers_teacher_id");

                    b.HasKey("CollegesCollegeId", "TeachersTeacherId")
                        .HasName("pk_college_teacher");

                    b.HasIndex("TeachersTeacherId")
                        .HasDatabaseName("ix_college_teacher_teachers_teacher_id");

                    b.ToTable("college_teacher", (string)null);
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<string>("CoursesCourseId")
                        .HasColumnType("text")
                        .HasColumnName("courses_course_id");

                    b.Property<string>("StudentsStudentId")
                        .HasColumnType("text")
                        .HasColumnName("students_student_id");

                    b.HasKey("CoursesCourseId", "StudentsStudentId")
                        .HasName("pk_course_student");

                    b.HasIndex("StudentsStudentId")
                        .HasDatabaseName("ix_course_student_students_student_id");

                    b.ToTable("course_student", (string)null);
                });

            modelBuilder.Entity("CourseTeacher", b =>
                {
                    b.Property<string>("CoursesCourseId")
                        .HasColumnType("text")
                        .HasColumnName("courses_course_id");

                    b.Property<string>("TeachersTeacherId")
                        .HasColumnType("text")
                        .HasColumnName("teachers_teacher_id");

                    b.HasKey("CoursesCourseId", "TeachersTeacherId")
                        .HasName("pk_course_teacher");

                    b.HasIndex("TeachersTeacherId")
                        .HasDatabaseName("ix_course_teacher_teachers_teacher_id");

                    b.ToTable("course_teacher", (string)null);
                });

            modelBuilder.Entity("backend.Models.DTO.Teacher.CourseTeacherResult", b =>
                {
                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_title");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("teacher_id");

                    b.ToTable("course_teacher_result", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("backend.Models.Domain.Colleges.College", b =>
                {
                    b.Property<string>("CollegeId")
                        .HasColumnType("text")
                        .HasColumnName("college_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("UniversityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("university_id");

                    b.HasKey("CollegeId")
                        .HasName("pk_colleges");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_colleges_university_id");

                    b.ToTable("colleges", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Articles.Article", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text")
                        .HasColumnName("article_id");

                    b.Property<string>("AuthorId")
                        .HasColumnType("text")
                        .HasColumnName("author_id");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator_id");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_posted");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headline");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tagline");

                    b.HasKey("ArticleId")
                        .HasName("pk_articles");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_articles_author_id");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Articles.Author", b =>
                {
                    b.Property<string>("AuthorId")
                        .HasColumnType("text")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_type");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("campus_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("AuthorId")
                        .HasName("pk_authors");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Assignments.Assignment", b =>
                {
                    b.Property<string>("AssignmentId")
                        .HasColumnType("text")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_date");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_id");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submission_date");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("teacher_id");

                    b.HasKey("AssignmentId")
                        .HasName("pk_assignments");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_assignments_course_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_assignments_teacher_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Assignments.Submission", b =>
                {
                    b.Property<string>("SubmissionId")
                        .HasColumnType("text")
                        .HasColumnName("submission_id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignment_id");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("Score")
                        .HasColumnType("text")
                        .HasColumnName("score");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.HasKey("SubmissionId")
                        .HasName("pk_submissions");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_submissions_assignment_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_submissions_student_id");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Attendances.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attendance_date");

                    b.Property<string>("StudentPresenceJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_presence_json");

                    b.HasKey("Id")
                        .HasName("pk_attendances");

                    b.ToTable("attendances", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Events.Event", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator_id");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_posted");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("DirectedTo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("directed_to");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("EventId")
                        .HasName("pk_events");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.FAQs.FAQ", b =>
                {
                    b.Property<int>("FAQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("faq_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FAQId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.HasKey("FAQId")
                        .HasName("pk_faqs");

                    b.ToTable("faqs", (string)null);

                    b.HasData(
                        new
                        {
                            FAQId = 1,
                            Answer = "Visit the university website and fill out the online application form.",
                            Category = "Admissions",
                            Question = "How do I apply for admission?"
                        },
                        new
                        {
                            FAQId = 2,
                            Answer = "You'll need transcripts, identification, and recommendation letters.",
                            Category = "Admissions",
                            Question = "What documents are required for admission?"
                        },
                        new
                        {
                            FAQId = 3,
                            Answer = "Tuition fees vary by program; visit the fees section on our website.",
                            Category = "Fees",
                            Question = "What are the tuition fees for undergraduate programs?"
                        },
                        new
                        {
                            FAQId = 4,
                            Answer = "Yes, scholarships and financial aid programs are available for eligible students.",
                            Category = "Financial Aid",
                            Question = "Is financial aid available?"
                        },
                        new
                        {
                            FAQId = 5,
                            Answer = "Log in to the student portal to check the status of your application.",
                            Category = "Admissions",
                            Question = "How can I check my application status?"
                        },
                        new
                        {
                            FAQId = 6,
                            Answer = "The academic calendar is available on the university website under 'Academic Resources'.",
                            Category = "General",
                            Question = "Where can I find the academic calendar?"
                        },
                        new
                        {
                            FAQId = 7,
                            Answer = "The university offers a wide range of programs including Engineering, Business, and Arts.",
                            Category = "Academics",
                            Question = "What majors does the university offer?"
                        },
                        new
                        {
                            FAQId = 8,
                            Answer = "Yes, but you need to complete a major change request form through the academic office.",
                            Category = "Academics",
                            Question = "Can I change my major after admission?"
                        },
                        new
                        {
                            FAQId = 9,
                            Answer = "The university follows a GPA-based grading system ranging from A to F.",
                            Category = "Academics",
                            Question = "What is the grading system?"
                        },
                        new
                        {
                            FAQId = 10,
                            Answer = "You can register through the student portal during the enrollment period.",
                            Category = "Registration",
                            Question = "How do I register for courses?"
                        },
                        new
                        {
                            FAQId = 11,
                            Answer = "Yes, several programs offer online or hybrid learning options.",
                            Category = "Academics",
                            Question = "Can I take online courses?"
                        },
                        new
                        {
                            FAQId = 12,
                            Answer = "Yes, the university provides on-campus and off-campus housing options.",
                            Category = "Facilities",
                            Question = "Is hostel accommodation available?"
                        },
                        new
                        {
                            FAQId = 13,
                            Answer = "After admission, the university provides required documents for visa applications.",
                            Category = "International Students",
                            Question = "How do I apply for a student visa?"
                        },
                        new
                        {
                            FAQId = 14,
                            Answer = "The university offers a gym, swimming pool, and various sports fields.",
                            Category = "Facilities",
                            Question = "What sports facilities are available?"
                        },
                        new
                        {
                            FAQId = 15,
                            Answer = "Yes, students can work up to 20 hours per week on campus.",
                            Category = "General",
                            Question = "Can I work while studying?"
                        },
                        new
                        {
                            FAQId = 16,
                            Answer = "Student ID cards are issued by the administration office during orientation.",
                            Category = "General",
                            Question = "How do I get a student ID card?"
                        },
                        new
                        {
                            FAQId = 17,
                            Answer = "Use the 'Forgot Password' option on the login page.",
                            Category = "Technical Support",
                            Question = "How do I reset my student portal password?"
                        },
                        new
                        {
                            FAQId = 18,
                            Answer = "Exam results are typically published within three weeks after exams.",
                            Category = "Academics",
                            Question = "When will my exam results be released?"
                        },
                        new
                        {
                            FAQId = 19,
                            Answer = "Tuition refunds are available under specific conditions; refer to the refund policy.",
                            Category = "Fees",
                            Question = "Can I get a refund for my tuition fees?"
                        },
                        new
                        {
                            FAQId = 20,
                            Answer = "Some programs require internships as part of the curriculum.",
                            Category = "Academics",
                            Question = "Are internships mandatory?"
                        },
                        new
                        {
                            FAQId = 21,
                            Answer = "There are many clubs and organizations students can join.",
                            Category = "Student Life",
                            Question = "What extracurricular activities are available?"
                        },
                        new
                        {
                            FAQId = 22,
                            Answer = "Assignments can be submitted via the student portal or email, as instructed.",
                            Category = "Academics",
                            Question = "How do I submit my assignments?"
                        },
                        new
                        {
                            FAQId = 23,
                            Answer = "You can file a formal complaint through the student services office.",
                            Category = "General",
                            Question = "What should I do if I have a complaint?"
                        },
                        new
                        {
                            FAQId = 24,
                            Answer = "Yes, the university partners with several institutions worldwide.",
                            Category = "International Students",
                            Question = "Does the university offer exchange programs?"
                        },
                        new
                        {
                            FAQId = 25,
                            Answer = "You can reach them via email or during office hours.",
                            Category = "Academics",
                            Question = "How can I contact my professors?"
                        },
                        new
                        {
                            FAQId = 26,
                            Answer = "Yes, you can apply for admission deferral for up to one year.",
                            Category = "Admissions",
                            Question = "Can I defer my admission?"
                        },
                        new
                        {
                            FAQId = 27,
                            Answer = "Transcripts can be requested via the registrar's office.",
                            Category = "Academics",
                            Question = "How can I request my transcripts?"
                        },
                        new
                        {
                            FAQId = 28,
                            Answer = "Yes, there is a health center for students.",
                            Category = "Facilities",
                            Question = "Is medical assistance available on campus?"
                        },
                        new
                        {
                            FAQId = 29,
                            Answer = "Reach out to faculty members leading research in your field of interest.",
                            Category = "Academics",
                            Question = "How do I join a research project?"
                        },
                        new
                        {
                            FAQId = 30,
                            Answer = "Yes, students can apply for parking permits.",
                            Category = "Facilities",
                            Question = "Is parking available on campus?"
                        },
                        new
                        {
                            FAQId = 31,
                            Answer = "Certificates are issued after graduation from the registrar’s office.",
                            Category = "Academics",
                            Question = "How do I get my degree certificate?"
                        },
                        new
                        {
                            FAQId = 32,
                            Answer = "Yes, the university has a career center to assist students.",
                            Category = "Student Life",
                            Question = "Are there job placement services?"
                        },
                        new
                        {
                            FAQId = 33,
                            Answer = "Yes, student ID cards may offer discounts on public transport.",
                            Category = "General",
                            Question = "Can I use my student ID for public transport?"
                        },
                        new
                        {
                            FAQId = 34,
                            Answer = "Yes, the university provides multiple dining options.",
                            Category = "Facilities",
                            Question = "Is there a cafeteria on campus?"
                        },
                        new
                        {
                            FAQId = 35,
                            Answer = "You need to apply for a make-up exam with valid reasons.",
                            Category = "Academics",
                            Question = "What if I miss an exam?"
                        },
                        new
                        {
                            FAQId = 36,
                            Answer = "Advisors are assigned based on your major; details are available in the portal.",
                            Category = "Academics",
                            Question = "How do I find academic advisors?"
                        },
                        new
                        {
                            FAQId = 37,
                            Answer = "Only service animals are allowed in dorms and classes.",
                            Category = "General",
                            Question = "Can I bring my pet to campus?"
                        },
                        new
                        {
                            FAQId = 38,
                            Answer = "Yes, the university offers accessibility support services.",
                            Category = "Facilities",
                            Question = "Are there special services for disabled students?"
                        },
                        new
                        {
                            FAQId = 39,
                            Answer = "Lost items should be reported to campus security.",
                            Category = "General",
                            Question = "Where can I report lost items?"
                        },
                        new
                        {
                            FAQId = 40,
                            Answer = "Elections are organized by the student council; check the portal for dates.",
                            Category = "Student Life",
                            Question = "How do I participate in student elections?"
                        });
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Files.FileDomain", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<string>("FileDescription")
                        .HasColumnType("text")
                        .HasColumnName("file_description");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_in_bytes");

                    b.HasKey("FileId")
                        .HasName("pk_files");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Help.Answer", b =>
                {
                    b.Property<string>("AnswerId")
                        .HasColumnType("text")
                        .HasColumnName("answer_id");

                    b.Property<string>("AnswerById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_by_id");

                    b.Property<string>("AnswerDetails")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_details");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.HasKey("AnswerId")
                        .HasName("pk_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_answers_question_id");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Help.Question", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.PrimitiveCollection<List<string>>("DirectedTo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("directed_to");

                    b.Property<string>("QuestionDetails")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_details");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.HasKey("QuestionId")
                        .HasName("pk_questions");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_questions_student_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Notices.Notice", b =>
                {
                    b.Property<string>("NoticeId")
                        .HasColumnType("text")
                        .HasColumnName("notice_id");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator_id");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_posted");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("DirectedTo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("directed_to");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("NoticeId")
                        .HasName("pk_notices");

                    b.ToTable("notices", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Results.Result", b =>
                {
                    b.Property<string>("ResultId")
                        .HasColumnType("text")
                        .HasColumnName("result_id");

                    b.Property<string>("ExaminationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("examination_type");

                    b.Property<string>("Percentage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("percentage");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("semester");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.HasKey("ResultId")
                        .HasName("pk_results");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_results_student_id");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Schedules.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.PrimitiveCollection<List<string>>("DirectedTo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("directed_to");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Syllabi.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("text")
                        .HasColumnName("course_id");

                    b.PrimitiveCollection<List<string>>("Books")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("books");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_description");

                    b.Property<string>("CourseObjective")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_objective");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_title");

                    b.Property<int>("CreditHour")
                        .HasColumnType("integer")
                        .HasColumnName("credit_hour");

                    b.Property<string>("FullMarks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_marks");

                    b.Property<string>("LabDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lab_description");

                    b.Property<string>("PassMarks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pass_marks");

                    b.Property<string>("SyllabusId")
                        .HasColumnType("text")
                        .HasColumnName("syllabus_id");

                    b.Property<bool>("isElective")
                        .HasColumnType("boolean")
                        .HasColumnName("is_elective");

                    b.HasKey("CourseId")
                        .HasName("pk_course");

                    b.HasIndex("SyllabusId")
                        .HasDatabaseName("ix_course_syllabus_id");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Syllabi.Syllabus", b =>
                {
                    b.Property<string>("SyllabusId")
                        .HasColumnType("text")
                        .HasColumnName("syllabus_id");

                    b.Property<string>("AllowedElectiveNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allowed_elective_no");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("semester");

                    b.HasKey("SyllabusId")
                        .HasName("pk_syllabus");

                    b.ToTable("syllabus", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Syllabi.Unit", b =>
                {
                    b.Property<string>("UnitId")
                        .HasColumnType("text")
                        .HasColumnName("unit_id");

                    b.Property<int>("CompletionHours")
                        .HasColumnType("integer")
                        .HasColumnName("completion_hours");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_id");

                    b.PrimitiveCollection<List<string>>("SubUnits")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sub_units");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("UnitId")
                        .HasName("pk_unit");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_unit_course_id");

                    b.ToTable("unit", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Students.Academic", b =>
                {
                    b.Property<string>("AcademicId")
                        .HasColumnType("text")
                        .HasColumnName("academic_id");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batch");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("faculty");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("semester");

                    b.HasKey("AcademicId")
                        .HasName("pk_academics");

                    b.ToTable("academics", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Students.Club", b =>
                {
                    b.Property<string>("ClubId")
                        .HasColumnType("text")
                        .HasColumnName("club_id");

                    b.Property<string>("ClubHeadId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("club_head_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ClubId")
                        .HasName("pk_clubs");

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Students.Financial", b =>
                {
                    b.Property<string>("FinancialId")
                        .HasColumnType("text")
                        .HasColumnName("financial_id");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric")
                        .HasColumnName("fee");

                    b.Property<bool>("FeePaid")
                        .HasColumnType("boolean")
                        .HasColumnName("fee_paid");

                    b.Property<decimal>("Scholarship")
                        .HasColumnType("numeric")
                        .HasColumnName("scholarship");

                    b.HasKey("FinancialId")
                        .HasName("pk_financials");

                    b.ToTable("financials", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Students.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<string>("AcademicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("academic_id");

                    b.Property<string>("CollegeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("college_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FinancialId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("financial_id");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<bool?>("isAuthor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_author");

                    b.Property<bool?>("isClubHead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_club_head");

                    b.HasKey("StudentId")
                        .HasName("pk_students");

                    b.HasIndex("AcademicId")
                        .HasDatabaseName("ix_students_academic_id");

                    b.HasIndex("CollegeId")
                        .HasDatabaseName("ix_students_college_id");

                    b.HasIndex("FinancialId")
                        .HasDatabaseName("ix_students_financial_id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Teachers.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("text")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("TeacherId")
                        .HasName("pk_teachers");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Universities.University", b =>
                {
                    b.Property<string>("UniversityId")
                        .HasColumnType("text")
                        .HasColumnName("university_id");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("UniversityId")
                        .HasName("pk_universities");

                    b.ToTable("universities", (string)null);
                });

            modelBuilder.Entity("ClubStudent", b =>
                {
                    b.HasOne("backend.Models.Domain.Students.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubsClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_club_student_clubs_clubs_club_id");

                    b.HasOne("backend.Models.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_club_student_students_students_student_id");
                });

            modelBuilder.Entity("CollegeTeacher", b =>
                {
                    b.HasOne("backend.Models.Domain.Colleges.College", null)
                        .WithMany()
                        .HasForeignKey("CollegesCollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_college_teacher_colleges_colleges_college_id");

                    b.HasOne("backend.Models.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_college_teacher_teachers_teachers_teacher_id");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("backend.Models.Domain.Content.Syllabi.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_student_course_courses_course_id");

                    b.HasOne("backend.Models.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_student_students_students_student_id");
                });

            modelBuilder.Entity("CourseTeacher", b =>
                {
                    b.HasOne("backend.Models.Domain.Content.Syllabi.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_teacher_course_courses_course_id");

                    b.HasOne("backend.Models.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_teacher_teachers_teachers_teacher_id");
                });

            modelBuilder.Entity("backend.Models.Domain.Colleges.College", b =>
                {
                    b.HasOne("backend.Models.Domain.Universities.University", "University")
                        .WithMany("Colleges")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_colleges_universities_university_id");

                    b.Navigation("University");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Articles.Article", b =>
                {
                    b.HasOne("backend.Models.Domain.Content.Articles.Author", null)
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("fk_articles_authors_author_id");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Assignments.Assignment", b =>
                {
                    b.HasOne("backend.Models.Domain.Content.Syllabi.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_course_course_id");

                    b.HasOne("backend.Models.Domain.Teachers.Teacher", "Teacher")
                        .WithMany("Assignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_teachers_teacher_id");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Assignments.Submission", b =>
                {
                    b.HasOne("backend.Models.Domain.Content.Assignments.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_assignments_assignment_id");

                    b.HasOne("backend.Models.Domain.Students.Student", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_students_student_id");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Help.Answer", b =>
                {
                    b.HasOne("backend.Models.Domain.Content.Help.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Help.Question", b =>
                {
                    b.HasOne("backend.Models.Domain.Students.Student", "Student")
                        .WithMany("Questions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_students_student_id");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Results.Result", b =>
                {
                    b.HasOne("backend.Models.Domain.Students.Student", "Student")
                        .WithMany("Results")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_results_students_student_id");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Syllabi.Course", b =>
                {
                    b.HasOne("backend.Models.Domain.Content.Syllabi.Syllabus", "Syllabus")
                        .WithMany("Courses")
                        .HasForeignKey("SyllabusId")
                        .HasConstraintName("fk_course_syllabus_syllabus_id");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Syllabi.Unit", b =>
                {
                    b.HasOne("backend.Models.Domain.Content.Syllabi.Course", "Course")
                        .WithMany("Units")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_course_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("backend.Models.Domain.Students.Student", b =>
                {
                    b.HasOne("backend.Models.Domain.Students.Academic", "Academic")
                        .WithMany("Students")
                        .HasForeignKey("AcademicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_academics_academic_id");

                    b.HasOne("backend.Models.Domain.Colleges.College", "College")
                        .WithMany("Students")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_colleges_college_id");

                    b.HasOne("backend.Models.Domain.Students.Financial", "Financial")
                        .WithMany("Students")
                        .HasForeignKey("FinancialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_financials_financial_id");

                    b.Navigation("Academic");

                    b.Navigation("College");

                    b.Navigation("Financial");
                });

            modelBuilder.Entity("backend.Models.Domain.Colleges.College", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Articles.Author", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Assignments.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Help.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Syllabi.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("backend.Models.Domain.Content.Syllabi.Syllabus", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("backend.Models.Domain.Students.Academic", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("backend.Models.Domain.Students.Financial", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("backend.Models.Domain.Students.Student", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Results");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("backend.Models.Domain.Teachers.Teacher", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("backend.Models.Domain.Universities.University", b =>
                {
                    b.Navigation("Colleges");
                });
#pragma warning restore 612, 618
        }
    }
}
